# Generated by Django 6.1.1 on 2026-10-02 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
            },
        ),
        migrations.CreateModel(
            name='RefBookVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('refbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='refbooks.refbooks')),
            ],
            options={
                'verbose_name': 'Версия справочника',
                'verbose_name_plural': 'Версии справочников',
            },
        ),
        migrations.CreateModel(
            name='RefBookElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='refbooks.refbookversion')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочника',
            },
        ),
        migrations.AddConstraint(
            model_name='refbookversion',
            constraint=models.UniqueConstraint(fields=('refbook', 'version'), name='unique_refbook_version'),
        ),
        migrations.AddConstraint(
            model_name='refbookversion',
            constraint=models.UniqueConstraint(fields=('refbook', 'start_date'), name='unique_refbook_start_date'),
        ),
        migrations.AddConstraint(
            model_name='refbookelement',
            constraint=models.UniqueConstraint(fields=('version', 'code'), name='unique_version_element_code'),
        ),
    ]
