# Generated by Django 6.1.1 on 2026-10-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refbooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Refbooks',
            new_name='Refbook',
        ),
    ]
